# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://meghdeepray.in
title: Meghdeep Ray
email: meghdeepr@gmail.com
author: Meghdeep Ray
description: > # "Write an awesome description for your new site here. 
    Meghdeep Ray's Personal Website
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    icon: envelope-o
    url: mailto:meghdeepr@gmail.com
  - title: twitter
    icon: twitter
    url: https://twitter.com/MeghdeepRay
  - title: github
    icon: github
    url: https://github.com/Meghdeep
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/meghdeepray/
  - title: stack overflow
    icon: stack-overflow
    url: https://stackoverflow.com/users/4358680/meghdeep-ray
  - title: quora
    icon: quora
    url: https://www.quora.com/Meghdeep-Ray
